version: '3.9'

services:
  #MongoDB Service
  mongo_db:
    container_name: mongo_db_midterm
    image: mongodb/mongodb-community-server
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes: 
      - mongo_db:/data/db

  #MongoDB GUI Service  
  mongo-gui:
    container_name: mongo_gui_midterm
    image: mongo-express
    restart: always
    depends_on: 
      - mongo_db
    ports:
      - 8020:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongo_db:27017/
    
  # Node API Service
  # node-api:
  #   build:
  #   ports:
  #     - 8000:8000
  #   environment:
  #     PORT: 8000
  #     MONGODB_URI: mongodb://mongo_db:27017
  #     DB_NAME: midterm_gigih 
  #   depends_on:
  #     - mongo_db

volumes:
  mongo_db: